let exc = Exception("This is the error message");

println(exc.message);

throw exc;
